// Emits the data behind the figures in the README.
//
// The figures are generated by running the library, not drawn by hand. Every
// number plotted comes out of the same pack and unpack the tests exercise, so a
// reader who does not believe a figure can regenerate it, and a figure cannot
// drift away from the code without the build noticing.
//
//   cmake --build build --target figures
//   ./build/Release/figures            writes docs/data/*.csv
//   node tools/render-figures.js       writes docs/*.svg

#include "state_channel.hpp"

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <string>

namespace sc = state_channel;

namespace {

// The scale used throughout the figures. Six decades, a caller-chosen range.
const sc::log_scale scale(1.0e-3, 1.0e3);

std::string bit_string(float value) {
    const std::uint32_t bits = sc::to_bits(value);
    std::string s;
    for (int i = 31; i >= 0; --i) {
        s.push_back(((bits >> i) & 1u) ? '1' : '0');
    }
    return s;
}

void write_bit_layout() {
    std::FILE* f = std::fopen("docs/data/bit-layout.csv", "w");
    if (!f) { std::perror("bit-layout.csv"); return; }

    const float diameter = 100.0e-6f;   // a 100 micrometre grain, in metres
    const double state = 12.5;          // a damage state, in the scale above

    const std::uint32_t code = scale.encode(state);
    const float packed = sc::pack(diameter, code);

    std::uint32_t recovered = 0u;
    sc::try_unpack(packed, recovered);
    const double decoded = scale.decode(recovered);

    std::fprintf(f, "field,value\n");
    std::fprintf(f, "before_bits,%s\n", bit_string(diameter).c_str());
    std::fprintf(f, "after_bits,%s\n", bit_string(packed).c_str());
    std::fprintf(f, "true_diameter_um,%.6f\n", diameter * 1.0e6);
    std::fprintf(f, "read_diameter_um,%.6f\n", static_cast<double>(packed) * 1.0e6);
    std::fprintf(f, "stripped_diameter_um,%.6f\n",
                 static_cast<double>(sc::strip(packed)) * 1.0e6);
    std::fprintf(f, "diameter_error_um,%.6f\n",
                 (static_cast<double>(packed) - static_cast<double>(diameter)) * 1.0e6);
    std::fprintf(f, "true_state,%.6f\n", state);
    std::fprintf(f, "decoded_state,%.6f\n", decoded);
    std::fprintf(f, "state_code,%u\n", code);
    std::fprintf(f, "state_error_percent,%.4f\n", 100.0 * (decoded - state) / state);
    std::fclose(f);
}

// What every other routine in the solver sees.
//
// Two views, because one cannot show both things. The error repeats with a
// period of one full field, which at 100 micrometres is 0.24 micrometres, so a
// plot wide enough to show the size range turns the structure into a solid
// block. The first file is zoomed in far enough to see the shape; the second
// gives up the shape and plots the worst case across the range.
void write_carrier_error() {
    std::FILE* f = std::fopen("docs/data/carrier-error.csv", "w");
    if (!f) { std::perror("carrier-error.csv"); return; }

    const std::uint32_t realised_code = scale.encode(12.5);

    std::fprintf(f, "diameter_um,realised_percent,envelope_low_percent,envelope_high_percent\n");
    constexpr int samples = 1200;
    for (int i = 0; i < samples; ++i) {
        const double d_um = 100.0 + 1.2 * i / (samples - 1);   // about five periods
        const float d = static_cast<float>(d_um * 1.0e-6);

        const float realised = sc::pack(d, realised_code);
        const float lowest = sc::pack(d, 0u);                  // smallest payload
        const float highest = sc::pack(d, sc::payload_max);    // largest payload

        auto percent = [&](float packed) {
            return 100.0 * (static_cast<double>(packed) - static_cast<double>(d)) /
                   static_cast<double>(d);
        };

        std::fprintf(f, "%.8f,%.8f,%.8f,%.8f\n", d_um, percent(realised), percent(lowest),
                     percent(highest));
    }
    std::fclose(f);

    // The worst case a grain of a given size can suffer. The whole field can be
    // rewritten, so the largest movement is field_mask units of the last
    // mantissa bit, and relative to the diameter that is largest when the
    // significand is 1 and smallest just below 2. Hence the resets at every
    // power of two, which is why a 100 micrometre grain and a 130 micrometre
    // grain do not get the same guarantee.
    f = std::fopen("docs/data/carrier-envelope.csv", "w");
    if (!f) { std::perror("carrier-envelope.csv"); return; }

    std::fprintf(f, "diameter_um,worst_percent,worst_um\n");
    for (int i = 0; i < 1200; ++i) {
        const double d_um = 40.0 * std::pow(400.0 / 40.0, static_cast<double>(i) / 1199.0);
        const float d = static_cast<float>(d_um * 1.0e-6);

        const std::uint32_t exponent = (sc::to_bits(d) & sc::exponent_mask) >> sc::mantissa_bits;
        const double power = std::ldexp(1.0, static_cast<int>(exponent) - 127);
        const double significand = static_cast<double>(d) / power;

        const double worst = sc::carrier_error_above / significand;
        std::fprintf(f, "%.8f,%.8f,%.8f\n", d_um, 100.0 * worst, worst * d_um);
    }
    std::fclose(f);
}

// What the channel gives back, across the whole state range and then zoomed in
// far enough to see the individual steps.
void write_state_roundtrip() {
    // Why the payload is log quantised rather than linearly quantised.
    //
    // Both schemes get the same 16384 codes. The log scale spends them so that
    // the relative resolution is the same everywhere, which is what a state
    // with multiplicative meaning needs. A linear scale spends nearly all of
    // them on the top decade and leaves the bottom of the range unusable.
    //
    // The error is the worst seen over a bin of samples, so the curve is the
    // envelope rather than the sawtooth inside it.
    std::FILE* f = std::fopen("docs/data/state-resolution.csv", "w");
    if (!f) { std::perror("state-resolution.csv"); return; }

    const double lo = 1.0e-3, hi = 1.0e3;

    auto linear_round_trip = [&](double state) {
        double t = (state - lo) / (hi - lo) * static_cast<double>(sc::payload_max);
        if (t < 0.0) t = 0.0;
        if (t > static_cast<double>(sc::payload_max)) t = static_cast<double>(sc::payload_max);
        const std::uint32_t code = static_cast<std::uint32_t>(std::floor(t + 0.5));
        return lo + static_cast<double>(code) * (hi - lo) / static_cast<double>(sc::payload_max);
    };

    std::fprintf(f, "state,log_worst_percent,linear_worst_percent\n");
    constexpr int bins = 90;
    constexpr int per_bin = 400;
    for (int b = 0; b < bins; ++b) {
        const double centre = std::pow(10.0, -3.0 + 6.0 * b / (bins - 1.0));
        double log_worst = 0.0, linear_worst = 0.0;

        for (int j = 0; j < per_bin; ++j) {
            // A narrow window about the bin centre, so the worst case inside a
            // quantisation step is actually reached.
            const double state = centre * (1.0 + 0.02 * (j / (per_bin - 1.0) - 0.5));
            if (state <= lo || state >= hi) continue;

            // The full path a state takes: quantise, pack into a diameter,
            // migrate, unpack, dequantise.
            const std::uint32_t code = scale.encode(state);
            const float carrier = sc::pack(100.0e-6f, code);
            std::uint32_t recovered = 0u;
            sc::try_unpack(carrier, recovered);
            const double decoded = scale.decode(recovered);

            const double log_error = std::fabs(decoded - state) / state;
            const double linear_error = std::fabs(linear_round_trip(state) - state) / state;
            if (log_error > log_worst) log_worst = log_error;
            if (linear_error > linear_worst) linear_worst = linear_error;
        }
        std::fprintf(f, "%.10g,%.8g,%.8g\n", centre, 100.0 * log_worst, 100.0 * linear_worst);
    }
    std::fclose(f);

    f = std::fopen("docs/data/state-zoom.csv", "w");
    if (!f) { std::perror("state-zoom.csv"); return; }

    std::fprintf(f, "true_state,decoded_state\n");
    for (int i = 0; i < 600; ++i) {
        const double state = 10.0 * (1.0 + 0.005 * i / 599.0 * 2.0);
        const std::uint32_t code = scale.encode(state);
        const float carrier = sc::pack(100.0e-6f, code);
        std::uint32_t recovered = 0u;
        sc::try_unpack(carrier, recovered);
        std::fprintf(f, "%.10g,%.10g\n", state, scale.decode(recovered));
    }
    std::fclose(f);
}

// The design decision itself: what a different payload width would have cost.
//
// Widening the payload buys states and costs carrier precision. The two move in
// opposite directions and at very different rates, because one is linear in the
// bits and the other is exponential in them. Fourteen is not a round number and
// it was not picked for looking like one.
void write_design_space() {
    std::FILE* f = std::fopen("docs/data/design-space.csv", "w");
    if (!f) { std::perror("design-space.csv"); return; }

    // The x axis is the whole field taken from the carrier, because that is
    // what the diameter pays. What the field buys depends on how much of it
    // goes to integrity: one bit for a flag, or seven for a checksum.
    std::fprintf(f, "field_bits,carrier_percent,state_flag_percent,state_guarded_percent,"
                    "states_flag,states_guarded\n");
    for (int field = 8; field <= 20; ++field) {
        const double carrier = 100.0 * sc::carrier_error_above_for(field - 1);
        const int flag_payload = field - 1;
        const int guarded_payload = field - sc::guarded::checksum_bits;

        const double state_flag = 100.0 * sc::state_resolution_for(flag_payload, 1.0e-3, 1.0e3);
        const double state_guarded =
            guarded_payload >= 1
                ? 100.0 * sc::state_resolution_for(guarded_payload, 1.0e-3, 1.0e3)
                : 0.0;

        std::fprintf(f, "%d,%.10g,%.10g,%.10g,%u,%u\n", field, carrier, state_flag, state_guarded,
                     sc::payload_max_for(flag_payload) + 1u,
                     guarded_payload >= 1 ? sc::payload_max_for(guarded_payload) + 1u : 0u);
    }
    std::fclose(f);
}

}  // namespace

int main() {
    write_bit_layout();
    write_carrier_error();
    write_state_roundtrip();
    write_design_space();
    std::printf("figure data written to docs/data\n");
    return 0;
}
